### ISSUE TITLE
Furion documentation - logging

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#100]

**Comment by microsofter** [comment]
前面的那个问题解决了。请问这种调用方式："我想把这个信息输出到日志文件".LogInformation();怎么没有把信息输出到控制台和日志文件？

**Comment by RookieCN** [comment]
18.9 关于日志文件重复生成问题; 
## .net6
的Program.cs已经不一样了，应该怎么写呢？

**Comment by jacoat** [comment]
Worker Service项目中 怎么注册和使用这个日志的拓展包？

**Comment by SunshineKui** [comment]
$"Info：{user.Name}".LogInformation();
我在没引用Furion.Extras.Logging.Serilog的时候，控制台是能打印信息的，在引用之后却没有能打印出信息。
另外当我改成_logger.LogInformation($"Info：{user.Name}");并在构造函数注入_logger后，可以在控制台打印出信息，
请问在引用Furion.Extras.Logging.Serilog后打印不了$"Info：{user.Name}".LogInformation();信息是什么情况？

**Comment by LGpan** [comment]
怎么在Program.cs输入日志

**Comment by MonkSoul** [comment]
![image](https://user-images.githubusercontent.com/22766122/175753042-043997d7-4e6e-4b69-85e6-6a4b420daa82.png)

**Comment by LGpan** [comment]
为什么单独输出文件的信息还在默认文件里面出现？
![QQ图片20220704143833](https://user-images.githubusercontent.com/23379926/177096506-8113a87e-092d-43f7-bc18-4adcd5eac005.png)
