### ISSUE TITLE
Furion documentation - http

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#101]

**Comment by happlyfox** [comment]
// 字典方式
await "https://www.furion.icu/post/{id}?name={name}&id={p.Id}".SetTemplates(new Dictionary<string , object> {
    { "id", 1 },
    { "name", "Furion" },
    { "p.Id", new Person { Id = 1 } }
});

这种方式经过测试并不能正确赋值

**Comment by xieyonghao1989** [comment]
像这样声明HttpClient代理，不能正常传递参数，是否是我的姿势没有摆正确喃？非数组的情况下是可以的


[Post("/api/user-center/bulk-create-or-update"), Client("UCSAPI")]
Task<RESTfulResult<UCSCompanyIdOutput[]>> BulkCreateOrUpdate([Body] UCSCompanyInput[] input);

**Comment by lmxin123** [comment]
[Interceptor(InterceptorTypes.Request)]
OnRequesting(HttpRequestMessage req)
全局拦截器中，在post请求下，怎么拿到body参数

**Comment by jiachunhui** [comment]
远程请求接口时，需要注意一点。

这里指的被远程请求的接口
接口返回值不能直接return (如果直接return 方法，会报错)
解决办法是，var res=xxxx(); return res;  这样就正常了。
这个问题卡了一晚上，记录这里，希望也帮助他人
