### ISSUE TITLE
Furion documentation - event-bus

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#104]

**Comment by xieyonghao1989** [comment]
请问一下，怎么设置消息只隶属于单个程序，而不被其它程序抢占喃？

**Comment by MonkSoul** [comment]
> 

不是很明白这个单个程序的边界是什么，是独立的程序，还是说程序集或者是项目？

**Comment by xieyonghao1989** [comment]
> @MonkSoul
> > 
> 
> 不是很明白这个单个程序的边界是什么，是独立的程序，还是说程序集或者是项目？

比如说在同一台服务器中，有3个站点，站点1发布的消息会被站点2、站点3监听订阅到(当然这个功能非常有用)，现在只想站点1发布的消息只能站点1订阅。

**Comment by 312855935** [comment]
个人愚见，即使收到也可以过滤掉不展示的吧？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MonkSoul/Furion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月29日(星期三) 下午3:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [MonkSoul/Furion] Furion documentation - event-bus (Issue #104)





  
@MonkSoul
   
不是很明白这个单个程序的边界是什么，是独立的程序，还是说程序集或者是项目？
  
比如说在同一台服务器中，有3个站点，站点1发布的消息会被站点2、站点3监听订阅到(当然这个功能非常有用)，现在只想站点1发布的消息只能站点1订阅。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiachunhui** [comment]
22.4 自定义事件发布者
代码里  public ChannelEventPublisher(IEventSourceStorer eventSourceStorer) 这行是不是写错了，应该
public ToDoEventPublisher (IEventSourceStorer eventSourceStorer)

**Comment by zacharyliang** [comment]
>在 Furion 中可以不用通过 buidler.AddSubscriber<T>() 方式一一注册，只需要实现 ISingleton 接口即可

这个现在是不是失效了，还是要在setup里配置啊

**Comment by liujinwww** [comment]
您好 我想咨询一下，一次发布，订阅的时候会获取两条重复的订阅。

**Comment by nicholasyin** [comment]
Kafka、RabbitMQ、ActiveMQ，和Redis、SQL Server、MySql，这是两个概念吧，前面是消息队列负责分发消息，后面是持久化存储消息，做的事情不一样。在Furion里给合并成一个概念了？

**Comment by dymproject** [comment]
> @liujinwww
> 您好 我想咨询一下，一次发布，订阅的时候会获取两条重复的订阅。

请问这个问题解决了吗，我也遇到了

**Comment by liujinwww** [comment]
@

> > @liujinwww
> > 您好 我想咨询一下，一次发布，订阅的时候会获取两条重复的订阅。
> 
> 请问这个问题解决了吗，我也遇到了

没解决呢。程序逻辑做处理，重复就忽略掉

**Comment by dymproject** [comment]
> @
> 
> > > @liujinwww
> > > 您好 我想咨询一下，一次发布，订阅的时候会获取两条重复的订阅。
> > 
> > 
> > 请问这个问题解决了吗，我也遇到了
> 
> 没解决呢。程序逻辑做处理，重复就忽略掉

发现问题所在了。我这边是继承了ISingleton，又注册了订阅服务，取消一个就好了。您可以参考一下

**Comment by dymproject** [comment]
> @liujinwww
> 您好 我想咨询一下，一次发布，订阅的时候会获取两条重复的订阅。

发现问题所在了。我这边是继承了ISingleton，又注册了订阅服务，取消一个就好了。您可以参考一下

**Comment by xieyonghao1989** [comment]
自定义实现事件消息队列存储，读取时不知道填写什么KEY,如果是统一的KEY，那么可能存在不同的队列，就没有办法区分了

**Comment by PanGuoDong** [comment]
Subscriber事件订阅者 处理方法必须是 Task

**Comment by antbuster** [comment]
不是很明白，如何集成RabbitMQ呢
