### ISSUE TITLE
Furion documentation - process-service

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#107]

**Comment by ysq5202121** [comment]
4

**Comment by chrcao** [comment]
> 如果使用了 Furion 包后可实现自动注册。
多个worker，想跑其中一个，又不想删掉其他不跑的worker，怎么办？

**Comment by jacoat** [comment]
Inject() 方法注册了 日志、缓存等服务，那还需要注册日志服务吗？

**Comment by AnsonWang0728** [comment]
有个疑问，如果是.net6怎么支持Windows服务呢？

**Comment by 0oHalao0** [comment]
请问.net 6项目无法在windows环境启动FurionWorkerServices是什么原因呢 @MonkSoul 
![image](https://user-images.githubusercontent.com/25733603/169999970-c14cc892-f7fd-4aa3-b37d-0e164f926883.png)
![image](https://user-images.githubusercontent.com/25733603/170000139-5c390cd9-fa1a-4d71-9449-3ecbf9792c02.png)

**Comment by vfplt** [comment]
Worker Service 除了可以独立部署到操作系统上以外，还支持在网站中配置，也就是同一宿主。
使用非常简单，只需要在 Startup.cs 中注册 Worker Service 接口，支持两种方式，如：
service.AddHostedService<你的WorkerService类>();

**引用官司方：实际调试没有成功，web api  和worker service.如何同一宿主。目前调试发现的2种方式冲突的，不能同时存在。请大佬指导。**
