### ISSUE TITLE
Furion documentation - job

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#108]

**Comment by shawn-show** [comment]
根据源码
```csharp

if (timer.ExecuteType == SpareTimeExecuteTypes.Serial)
{
    if (!currentRecord.IsCompleteOfPrev) return;

    // 立即更新多线程状态
    currentRecord.IsCompleteOfPrev = false;
    UpdateWorkerRecord(workerName, currentRecord);
}
```
当串行执行时，第二个任务不是被同步锁锁住而是直接return，跳过去。非常好！

**Comment by MonkSoul** [comment]
> 

没明白意思，这是是有问题还是没问题啊。

**Comment by MonkSoul** [comment]
> 根据源码
> 
> ```cs
> if (timer.ExecuteType == SpareTimeExecuteTypes.Serial)
> {
>     if (!currentRecord.IsCompleteOfPrev) return;
> 
>     // 立即更新多线程状态
>     currentRecord.IsCompleteOfPrev = false;
>     UpdateWorkerRecord(workerName, currentRecord);
> }
> ```
> 
> 当串行执行时，第二个任务不是被同步锁锁住而是直接return，跳过去。非常好！

没明白，这里是有问题还是没问题啊。

**Comment by chrcao** [comment]
串行运行,在interval小于等于15的时候，起始的几个action还是会并行运行
```c#
 SpareTime.Do(15, (timer, count) =>
            {
                Thread.Sleep(2000);
                Console.WriteLine("现在时间：" + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
                Console.WriteLine($"一共执行了：{count} 次");
            }, "jobName", "这是一个计时器任务", executeType: SpareTimeExecuteTypes.Serial);
```

**Comment by pccai** [comment]
SpareTime.Start("jobName"); 手工执行任务，能否传递args参数进去呢？

**Comment by jiangzhuangxiansheng** [comment]
请问下，cron有没有获取比如最近N次执行时间的方法，类似：
2022-02-15 13:31:46
2022-02-15 13:31:47
2022-02-15 13:31:48
2022-02-15 13:31:49
2022-02-15 13:31:50
目前只看到下一次执行时间的方法

**Comment by a1113590485** [comment]
请问定时任务有持久化的方案吗，在更新代码至服务器时，若停止网站运行，则会导致所有进程都会失效

**Comment by lutan1212** [comment]
请问 JobWorker 如何调用 interface 里面的方法

**Comment by lutan1212** [comment]
请问 JobWorker 如何调用 interface 里面的方法
