### ISSUE TITLE
Furion documentation - deploy-docker

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#117]

**Comment by tangjiegege** [comment]
部署linux后SwaggerUI无法正常显示，接口是通的，
如下两张图，日志中没有任何报错显示
![image](https://user-images.githubusercontent.com/68260038/158011085-80d67352-b044-421e-93d3-d82b17e87aca.png)
![image](https://user-images.githubusercontent.com/68260038/158011090-1cd733ad-79b4-473b-8d6d-ce04cb28d4e6.png)
