### ISSUE TITLE
Furion documentation - virtual-deploy

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#119]

**Comment by lanfaboy** [comment]
.net6如何发布成二级网站

**Comment by lanfaboy** [comment]
。net 6发布成二级，按照 "AppSettings": {
    "VirtualPath": "/虚拟目录"
  }配置无效

**Comment by Schaffer-W** [comment]
作者你好，我怎么用了34.4.1.1的设置部署没有生效呢

**Comment by MonkSoul** [comment]
> @Schaffer-W
> 作者你好，我怎么用了34.4.1.1的设置部署没有生效呢

已经更新了文档了，也提供了视频教程：https://www.bilibili.com/video/BV1Rv4y1P7ZB

**Comment by Schaffer-W** [comment]
> @MonkSoul
> > @Schaffer-W
> > 作者你好，我怎么用了34.4.1.1的设置部署没有生效呢
> 
> 已经更新了文档了，也提供了视频教程：https://www.bilibili.com/video/BV1Rv4y1P7ZB

好的，谢谢。这个开发文档旧版本在哪里可以找到啊
