### ISSUE TITLE
Furion documentation - unittest

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#122]

**Comment by pccai** [comment]
Net6下是不是不需要.UseStartup<Startup>());呢，加了后提示： Scheme already exists: Bearer

**Comment by pccai** [comment]
发现每次都要create一个新的scope才能继续：

 [Fact]
    public async Task Test_JobService()
    {
        using (var scope = _factory.Services.CreateScope())
        {
            var _job = scope.ServiceProvider.GetRequiredService<IJobService>();
