### ISSUE TITLE
Furion documentation - app

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#130]

**Comment by 96contione** [comment]
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/30228177/150303522-236e10d8-d172-41ff-84b9-dfece93132dd.png)

**Comment by MonsterUncle** [comment]
> @96contione
> ![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/30228177/150303522-236e10d8-d172-41ff-84b9-dfece93132dd.png)
> 

试试用using

**Comment by MonkSoul** [comment]
> @96contione
> ![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/30228177/150303522-236e10d8-d172-41ff-84b9-dfece93132dd.png)
> 

注意下面的 `UnmanagedObjects.Add(scoped)` 未托管对象管理，会自动请求结束释放。
