### ISSUE TITLE
Furion documentation - jwt

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#143]

**Comment by jiachunhui** [comment]
#### 自己遇到的问题

1.读取配置信息生成 Token

`var token = JWTEncryption.Encrypt(new Dictionary<string, object> { { "UserId", 1 }  });`

2. 配置 Token 密钥

`var token = JWTEncryption.Encrypt("monksoul@outlook.com", new Dictionary<string, object> { { "UserId", 1 }  });`

起初，我以为，这两个方法结果会是一样的，实际是不一样的。这两个方法处理参数Payload不一样。

##### 我的解决办法 ,是我懒的去写，还是默认配置里，只需要修改一下密钥

>public static string Encrypt(string issuerSigningKey, IDictionary<string, object> payload, long? expiredTime = null)
>
>		{
>
>			var (Payload, JWTSettings) = CombinePayload(payload, expiredTime);//重点在这里不一样
>
>			return Encrypt(issuerSigningKey, Payload, JWTSettings.Algorithm);
>
>		}
>
>
