### ISSUE TITLE
Who use Furion?

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#154]

**Comment by denisding** [comment]
你好，Furion，我们正在准备在新项目中使用 Furion，这是我们的网址：http://www.flowportal.com/

**Comment by MonkSoul** [comment]
> 你好，Furion，我们正在准备在新项目中使用 Furion，这是我们的网址：http://www.flowportal.com/

好的，感谢，Github 我很少用哦，所以代码东西都在国内 Gitee：https://gitee.com/dotnetchina/Furion，Github 只做代码同步。

Furion 完全开源免费，无限制，无授权，无商业。
