### ISSUE TITLE
Have you considered providing english doc?

### ISSUE THREAD

**Issue by mss0517** [MonkSoul/Furion#178]
常常想推荐给国外的朋友，但中文他们都看不太懂，虽然透过机翻还是能看个大概。
如果有英文文档估计Furion全球都能火吧，也说不定能吸到更多国外大佬贡献。

**Comment by MonkSoul** [comment]
英文文档在今年年初就考虑了，只不过之前一直都在紧急开发完善中，经过两年多的迭代，现在已经成熟稳定，已经着手编写英文文档了，不过进度很慢。

很感谢您将 Furion 分享给国际友人，也非常感谢您的信任和支持，我这边团队将抓紧时间推出英文文档。

**Comment by mss0517** [comment]
辛苦了 相当期待！
