### ISSUE TITLE
关于Worker Service依赖注入的问题

### ISSUE THREAD

**Issue by tonyjianhu** [MonkSoul/Furion#187]
作者您好，我看到您在worker service里面注入非单例服务的方式是在while循环内创建一个scope，如果我把创建scope提到while循环外，那么是否就类似于单例了（因为worker service 会一直运行，直到程序结束），这样会不会更加好一点？
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/29139627/205585006-8561a4e3-ccf3-4738-8547-03e3aaecd458.png">

**Comment by MonkSoul** [comment]
不好意思，由于这几天不能访问 `Github`（但收到了邮件），无法回复您，今天终于上来了。

我很少用 `Github`，我都是使用 `Gitee` 的，有问题可以在 `Gitee` 发 `Issue` ，[https://gitee.com/dotnetchina/Furion](https://gitee.com/dotnetchina/Furion)

另外您的建议是对的，为此我更新了文档，感谢。[https://furion.baiqian.ltd/docs/25.5 依赖注入使用](https://furion.baiqian.ltd/docs/process-service#255-%E4%BE%9D%E8%B5%96%E6%B3%A8%E5%85%A5%E4%BD%BF%E7%94%A8)

![image](https://user-images.githubusercontent.com/22766122/206080874-a5a36063-63cb-4f40-ba60-3f3a934a27db.png)

**Comment by MonkSoul** [comment]
Gitee 平台非常活跃：

![image](https://user-images.githubusercontent.com/22766122/206081135-29611926-80c9-40b9-83ec-74c27d2b6100.png)

Issue 已经解决了 1847个了：[https://gitee.com/dotnetchina/Furion/issues](https://gitee.com/dotnetchina/Furion/issues)

![image](https://user-images.githubusercontent.com/22766122/206081173-922b823a-78e6-49bf-b06f-3b86b7193793.png)
