### ISSUE TITLE
在vs2022中，控制台启动api无法唤起浏览器，而iis可以

### ISSUE THREAD

**Issue by yaolc** [MonkSoul/Furion#192]
![1673279141849](https://user-images.githubusercontent.com/49051136/211348846-6db4f1c7-d62c-4a66-92f7-b6cff79d7cbc.png)
![1673279153888](https://user-images.githubusercontent.com/49051136/211348891-415e55d0-ef9f-44d4-a2be-d8cc91d811fb.png)
代码和相关启动配置如图所示。控制台启动，无法唤起浏览器（而如果是新建的netcore webapi控制台可以唤起浏览器）。iis则正常都可以唤起浏览器。请问还有哪里需要配置？

**Comment by yaolc** [comment]
经测试，修改图中这句话，可以解决这个问题。
![1673279536533](https://user-images.githubusercontent.com/49051136/211350470-68d410ea-9e12-4b32-a85a-d79e37647c4d.png)

**Comment by MonkSoul** [comment]
编辑控制台 `.csproj` 文件，修改 `Project` 节点值，添加 `.Web`，如：

![image](https://user-images.githubusercontent.com/22766122/211440063-1ef80e70-6c3c-4d93-8bb1-e258e02d0853.png)

-----

另外，`Github` 只做代码同步哦，所有 `Issue` 和 `PR` 都是在 `Gitee` 上进行：[https://gitee.com/dotnetchina/Furion](https://gitee.com/dotnetchina/Furion)
