### ISSUE TITLE
你好，Furion，我们正在准备在新项目中使用 Furion，这是我们的网址：http://cy-coo.com/

### ISSUE THREAD

**Issue by yang131490** [MonkSoul/Furion#193]
你好，Furion，我们正在准备在新项目中使用 Furion，这是我们的网址：http://cy-coo.com/

**Comment by MonkSoul** [comment]
好的，感谢感谢，`Github` 我很少用哦，都是 `Gitee`，`Gitee` 贡献者都有231个人，Issue 都快 2000 了，[https://gitee.com/dotnetchina/Furion](https://gitee.com/dotnetchina/Furion)
