### ISSUE TITLE
DataValidation FromQuery 值可空时问题

### ISSUE THREAD

**Issue by tanqilong** [MonkSoul/Furion#195]
![微信图片_1](https://user-images.githubusercontent.com/19204352/215409665-7bdef8e7-7dd0-4bc0-9301-9b95a56ddacb.png)
![微信图片_2](https://user-images.githubusercontent.com/19204352/215409695-e23aeee3-ced0-4d7f-b80a-9f2725d8f4d8.png)
![微信图片_3](https://user-images.githubusercontent.com/19204352/215409723-f03819d7-be85-4128-b43d-eef1512ab2fc.png)
![微信图片_4](https://user-images.githubusercontent.com/19204352/215409745-ff31558e-b0d5-47fc-b38b-b4978a956a3b.png)

**Comment by MonkSoul** [comment]
这是 `C# 8.0` 的行为，可关闭，另外 `Github` 只做代码同步用，有问题到 `Gitee` ：[https://gitee.com/dotnetchina/Furion](https://gitee.com/dotnetchina/Furion)

![image](https://user-images.githubusercontent.com/22766122/215413905-19f98319-54f2-42b5-ac44-d1c7ddae879c.png)

![image](https://user-images.githubusercontent.com/22766122/215414078-0e1f031f-fde3-4488-8ea7-309e910c7234.png)

**Comment by tanqilong** [comment]
改成false了，没起作用

**Comment by tanqilong** [comment]
int 也不是引用类型啊，应该跟这个配置没关系

**Comment by tanqilong** [comment]
> 这是 `C# 8.0` 的行为，可关闭，另外 `Github` 只做代码同步用，有问题到 `Gitee` ：https://gitee.com/dotnetchina/Furion
> 
> ![image](https://user-images.githubusercontent.com/22766122/215413905-19f98319-54f2-42b5-ac44-d1c7ddae879c.png)
> 
> ![image](https://user-images.githubusercontent.com/22766122/215414078-0e1f031f-fde3-4488-8ea7-309e910c7234.png)

改成false了，没起作用，int 也不是引用类型啊，应该跟这个配置没关系
