### ISSUE TITLE
无法跟踪实体

### ISSUE THREAD

**Issue by ataoliu** [MonkSoul/Furion#197]
![Dingtalk_20230213162151](https://user-images.githubusercontent.com/69141308/218406611-a18ddadf-4277-4235-aabf-919ccc08326c.jpg)

在这个上一层的一个方法用这个_repository查询后修改了一些值 紧接着保存 
报错:
The instance of entity type 'CertApplyRecordEntity' cannot be tracked because another instance with the key value '{Id: af71ff63-1db0-4293-b162-fb6744f7456c}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.”

**Comment by ataoliu** [comment]
![11111](https://user-images.githubusercontent.com/69141308/218407541-21e1acca-0854-4a6b-b9c9-131ed9942655.jpg)

**Comment by MonkSoul** [comment]
这是 `efcore` 的错误，意思是你多个线程操作（多个实例）操作同一个对象了。，，，

**Comment by ataoliu** [comment]
那有什么方法可以解决呢
