### ISSUE TITLE
请问怎么让多个间隔时间相同的定时作业在项目启动的时候不在同一时间一起执行

### ISSUE THREAD

**Issue by 0xlane** [MonkSoul/Furion#200]
比如我有个定时作业A每隔5分钟执行，还有有个定时作业B也是每隔5分钟执行。
不同的IJob之间可以设置串行运行吗，要不然在项目启动的时候如果作业过多会导致这么多作业在同一时间运行

**Comment by MonkSoul** [comment]
没有不同作业串行的功能。另外每一个作业都是新的线程执行。

另外 `Github` 只做代码同步，有问题请到 `Gitee`：[https://gitee.com/dotnetchina/Furion](https://gitee.com/dotnetchina/Furion)
