### ISSUE TITLE
Furion documentation - case

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#43]

**Comment by MonkSoul** [comment]
大家基于 Furion 开发开源项目也可以点击 **Edit this page** 进行编辑。

**Comment by shuang7822** [comment]
这些项目，大多只是一张皮，并不是最佳实践
大多不能直接拿来用

**Comment by a1113590485** [comment]
furion中有没有指定方法超时自动跳入异常的方法呀，单单只是前端设置超时并没有作用，后台方法还是在一直运行的，无法从根源上直接结束掉方法执行

**Comment by Fanbin168** [comment]
IIS二级虚拟目录部署的问题麻烦解决：问题地址：https://gitee.com/dotnetchina/Furion/issues/I4PZ0C

**Comment by 0oHalao0** [comment]
> @shuang7822
> 这些项目，大多只是一张皮，并不是最佳实践
> 大多不能直接拿来用
程序员用别人的干嘛哈哈哈，就是自己写一套才爽

**Comment by heifengwll** [comment]
我这边在用 Pear Admin这个项目。

修改：

1、升级为Furion 3.4.2和.net 6.0

2、修改数据库为MySql和SqlServer

3、增加 个人基本资料修改和密码修改

4、增加头像功能

5、增加批量删除功能

6、修正api接口访问方式，统一为 控制器/方法/参数

7、修正前端弹窗异常错误

8、真实项目正在使用，持续修复发现的错误，使之成为一个合格能用的模板框架。

9、需要修复后基础版本的请联系我，QQ369628105。免费提供
