### ISSUE TITLE
Furion documentation - get-start

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#47]

**Comment by MonkSoul** [comment]
**特别提醒**，`Furion` 默认内置了 `Swagger` 包，所以创建项目的时候无需包含 `Swagger` 包，否则会出现冲突。

**Comment by ntuchenxy** [comment]
我有一个窗体项目和web项目共用数据库，原先单窗体项目时就是简单services.AddDbContext注入就可以使用数据库里，但现在增加了一个web，我把数据库配置到web的脚手架里里，窗体项目引用EntityFramework.Core，能否提供下解决思路，现在这样如何在窗体里注入DbContext？

**Comment by shengguow** [comment]
Bravo! 華人之光!
