### ISSUE TITLE
Furion documentation - get-start-net6

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#48]

**Comment by MonkSoul** [comment]
学会了吗？有什么问题优先推荐在 Gitee 中发issue，或在这里评论哦！请大家文明用语。

**Comment by tywo45** [comment]
这个可以有

**Comment by MonkSoul** [comment]
> @tywo45
> 这个可以有

😁😂🤣😃😄😅😆😀😉😊😋😎😍😘🥰😗😙😚☺🙂🤗🤩🤔🤨

**Comment by sungdcn** [comment]
按操作说明，没有预期效果

**Comment by cuongpv88** [comment]
I got this error, when I used Furion for my .NET MAUI application.

There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'iossimulator-x64'.	MauiApp2	C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets

**Comment by dejex** [comment]
刚才那条是我漏了.Inject()和AddInject()两个指令，现在没错误了。但是有两个问题：

**Comment by dejex** [comment]
刚才漏了.Inject()和AddInject()两个指令，现在没错误了。但是有两个问题：

1. UseInject()地址是根目录，UseInject("api")也是根目录，似乎并不能改变这个目录
2. 没有出来swagger页面，浏览器有json数据返回

请大神指正！ 版本3.0.6

**Comment by NickNameIsNull** [comment]
Furion(3.0.6) 是取消了对MiniProfiler的支持吗？我创建的.NET6 MVC项目，在swagger的界面中并没有看到MiniProfiler，我看Furion的依赖中是有MiniProfiler.AspNetCore.Mvc(4.2.22)的

**Comment by 0oHalao0** [comment]
> @MonkSoul
> 学会了吗？有什么问题优先推荐在 Gitee 中发 [issue](https://gitee.com/dotnetchina/Furion/issues/new)，或在这里评论哦！请大家文明用语。😁

学废了

**Comment by MonkSoul** [comment]
> @0oHalao0
> > @MonkSoul
> > 学会了吗？有什么问题优先推荐在 Gitee 中发 [issue](https://gitee.com/dotnetchina/Furion/issues/new)，或在这里评论哦！请大家文明用语。😁
> 
> 学废了

顽皮~~😂
