### ISSUE TITLE
Furion documentation - template

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#49]

**Comment by selectweilin** [comment]
为啥使用Furion.Template.Mvc脚手架无法访问swagger文档

**Comment by mozhenshuang** [comment]
项目名称不支持短横线

**Comment by EEvil-G** [comment]
/Users/haosida_work/Projects/FurionApi/FurionApi/FurionApi.Core/FurionApi.Core.csproj: Error NU1102: Unable to find package Furion with version (>= 3.1.2)
  - Found 406 version(s) in nuget.org [ Nearest version: 3.1.1 ] (NU1102) (FurionApi.Core)

**Comment by RandolphLou** [comment]
> @mozhenshuang
> 项目名称不支持短横线

同有此问题

**Comment by ZingGeek** [comment]
大佬，脚手架项目啥时候改.net6版本？不改会有什么特性丢失不？主要变化是program.cs的写法？

**Comment by ntuchenxy** [comment]
furion的blazor是基于server的，如果基于WebAssembly的项目，似乎有冲突？
