### ISSUE TITLE
Furion documentation - appstartup

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#53]

**Comment by beikee** [comment]
配置这块 不读文档,就像个盲盒.  跟java 那些配置有什么差距了.c#之美就是少些配置.

**Comment by 312855935** [comment]
深有同感



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MonkSoul/Furion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午3:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [MonkSoul/Furion] Furion documentation - appstartup (Issue #53)





 
配置这块 不读文档,就像个盲盒.  跟java 那些配置有什么差距了.c#之美就是少些配置.

**Comment by luoxue2017** [comment]
[AppStartup(800)] 配置启动顺序有点另类，大型项目有几十上百个模块，跟进依赖逐个配置很累，容易出错，建议 参考 abp框架里面的模块依赖，跟进依赖自动安顺序加载。

**Comment by joyswing** [comment]
AppStartupAppStartup
