### ISSUE TITLE
Furion documentation - friendly-exception

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#58]

**Comment by kaishanguai-wo** [comment]
你好
throw Oops.Oh(SystemErrorCodes.u1007); 这里直接返回了错误message，怎么才能返回RESTfulResult类型的提示呢？
这个 Oops.Oh怎么不跳转到OnException里面呢？ 这个也配置了规范化结果异常处理的文件。
不懂，麻烦有时间了看下
![(4DJ0)6R)YG4YQHD$798CSW](https://user-images.githubusercontent.com/104826415/166426438-3b127338-83d8-42cf-994e-74618c92bcc9.png)
![H4B4@2VF~IG99CU9Y0YVV01](https://user-images.githubusercontent.com/104826415/166426461-be56d42f-996b-44fe-b243-1bcd621f1b3a.png)
