### ISSUE TITLE
Furion documentation - data-validation

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#59]

**Comment by xieyonghao1989** [comment]
现在框架中内置的Date类型格式yyyy-MM-dd HH:mm:ss能通过，内置的Time类型格式HH:mm:ss能通过。但是时间格式yyyy-MM-dd这两种方式都无法通过，希望增加ShortDate来验证yyyy-MM-dd

**Comment by DNLi303** [comment]
验证错误的返回格式是否可以自定义，或者是现在已有这个功能，因为为了保持接口格式的一致性

**Comment by xieyonghao1989** [comment]
请问一下，怎么实现可为空的字段，如果未传值则不再继续验证。比如一个字段打上了ValidationTypes.PositiveNumber的验证标记，如果前端发送过来的是值，则无需验证直接通过，如果有值则进行验证（因为数据库设计此字段是可为空的）

**Comment by cngrax** [comment]
> @DNLi303
> 验证错误的返回格式是否可以自定义，或者是现在已有这个功能，因为为了保持接口格式的一致性 

ConfigureServices里面，注入基本配置和规范化结果 .AddInjectWithUnifyResult() MyRESTfulResultProvider实现接口IUnifyResultProvider 然后里面可以重写OnValidateFailed方法，这里可以自定义错误的返回格式

**Comment by emptyO** [comment]
校验不通过时，怎么进入异常处理？

**Comment by tanqilong** [comment]
DataValidation FromQuery 值可空时问题
![微信图片_1](https://user-images.githubusercontent.com/19204352/215379250-41bd0390-76a2-4301-8648-c45899df12c9.png)
![微信图片_2](https://user-images.githubusercontent.com/19204352/215379283-6b4afe6f-f2d1-439b-9546-a2ab69e2d361.png)
![微信图片_3](https://user-images.githubusercontent.com/19204352/215379317-f411ba83-a9c1-43c5-9299-c088b6242934.png)
![微信图片_4](https://user-images.githubusercontent.com/19204352/215379343-8767044e-194e-43f1-b9b8-e541aac697ed.png)
