### ISSUE TITLE
Furion documentation - dbcontext-locator

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#62]

**Comment by xuzheng123** [comment]
![image](https://user-images.githubusercontent.com/13130337/147477016-1025113d-d224-4492-be90-e194fba28dcf.png)
![image](https://user-images.githubusercontent.com/13130337/147477051-a1ba51db-e782-44ce-8941-19018b914bb0.png)
为啥这里加上这个MultiTenantDbContextLocator 定位器会出现这个错，这是ps1生成的实体。
当我改成 public partial class SUser : IEntity<MultiTenantDbContextLocator>, IEntityTypeBuilder<SUser> 这么写就没问题。

**Comment by MonkSoul** [comment]
> ![image](https://user-images.githubusercontent.com/13130337/147477016-1025113d-d224-4492-be90-e194fba28dcf.png) ![image](https://user-images.githubusercontent.com/13130337/147477051-a1ba51db-e782-44ce-8941-19018b914bb0.png) 为啥这里加上这个MultiTenantDbContextLocator 定位器会出现这个错，这是ps1生成的实体。 ![image](https://user-images.githubusercontent.com/13130337/147477404-1148e827-3c11-413e-8f2e-931f662b7c56.png) 这么写就没问题。

`ps1` 命令也需要指定 `DbContextLocators` 参数。

**Comment by 17607165586** [comment]
切换数据时报错：Cannot create a DbSet for 'DBServer' because this type is not included in the model for the context 啥问题
