### ISSUE TITLE
Furion documentation - entity

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#63]

**Comment by dswfort** [comment]
建议标注9.3.4.1 在数据库实体中配置，`SomeClass `必须是`public`，我先前定义为`internal`后一直不生效，折腾了好几个小时

**Comment by cp2574** [comment]
> @dswfort
> 建议标注9.3.4.1 在数据库实体中配置，`SomeClass `必须是`public`，我先前定义为`internal`后一直不生效，折腾了好几个小时
我也遇到了
