### ISSUE TITLE
Furion documentation - dbcontext-sql

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#75]

**Comment by SunnyZhX** [comment]
当操作符为In时，参数应该如何传？
如： select * from 表1 where 字段 in (xx)

**Comment by yuansxx** [comment]
SqlAdoNetExtensions中ExecuteReader执行后未关闭数据库连接，高频查询数据库时会导致Pooled connection request timed out问题

**Comment by MonkSoul** [comment]
> SqlAdoNetExtensions中ExecuteReader执行后未关闭数据库连接，高频查询数据库时会导致Pooled connection request timed out问题

![image](https://user-images.githubusercontent.com/22766122/169199207-1b030be6-f445-4ab5-a069-d5db974f7793.png)

数据库连接对象由 `DatabaseFacade` 创建，统一交给 `EFCore` 的 `DbContext` 管理

**Comment by DaZhuangNiu** [comment]
有sql的分页方法吗
