### ISSUE TITLE
Furion documentation - dbcontext-multi-database

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#78]

**Comment by xieyonghao1989** [comment]
MySqlConnector.MySqlConnection链接只能读取到配置内的数据库信息，而无法读取到指定数据库信息

**Comment by xieyonghao1989** [comment]
public static DataTable GetDataTable(string connString, string sql)
        {
            DataTable dt = new DataTable("dt");
            using var conn = new MySqlConnector.MySqlConnection(connString);
            //判断连接状态
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            var reader = conn.ExecuteReader(sql);
            dt.Load(reader);
            conn.Close();
            return dt;
        }

**Comment by xieyonghao1989** [comment]
怎么删除自己的评论喃，感觉放出来搞笑

**Comment by jiachunhui** [comment]
'OFFSET' 附近有语法错误。\r\n在 FETCH 语句中选项 NEXT 的用法无效。
SQL Server 2008不支持Fetch和Next语句（SQL Server 2012才支持）。

### 看SqlServer 兼容 2005-2008 写法
