### ISSUE TITLE
Furion documentation - dbcontext-code-first

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#80]

**Comment by EEvil-G** [comment]
macOS用户表示很痛苦...

**Comment by Arvinlan-github** [comment]
您好，我的业务场景有两个工程

一个是日志工程，它的实体对象是这么定义的 SysLogAudit : IEntity<LoggerDbContextLocator>，
上下文LoggerDbContext : AppDbContext<LoggerDbContext, LoggerDbContextLocator>

另一个是用户工程，它的上下文定义是DefaultDbContext : AppDbContext<DefaultDbContext>

用户工程引入日志工程。当我在用户工程执行code first进行数据迁移时，发现会把日志工程的SysLogAudit表带进来

指令是： Add-Migration 20220101 -Context DefaultDbContext 

请问该如何避免把日志工程的实体迁进用户工程？

**Comment by YinChen001** [comment]
遇到的一个小坑，生成迁移文件的时候，不要设置两个项目为启动项目，要设置Entry为启动项目 否则Add-Migration 会报错

**Comment by YinChen001** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
