### ISSUE TITLE
Furion documentation - dbcontext-filter

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#83]

**Comment by heifengwll** [comment]
![image](https://user-images.githubusercontent.com/14345063/176646924-b4b824a0-30f1-4f4a-a96f-899f42906618.png)
请问，全局查询筛选器这里怎么写才能支持多个筛选？
1、我这里配置了 多租户 和 IsDelete筛选
2、但实验发现，谁写在后面谁生效，前一个筛选器 没有生效。
3、比如 ，先写了多租户，后面写 软删除，只有 软删除的 筛选器生效。没有按当前租户过滤数据
请问下，这里怎么写才能同时支持多个筛选？

**Comment by heifengwll** [comment]
https://www.cnblogs.com/heifengwll/p/16433799.html
可以参考这个文章
