### ISSUE TITLE
Furion documentation - sqlsugar

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#90]

**Comment by Schaffer-W** [comment]
你好。10.1.4使用构造函数注入在哪里注入啊

**Comment by hawind** [comment]
SqlSugar.SqlSugarException:“中文提示 :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：Object reference not set to an instance of an object..
English Message : Connection open error . Object reference not set to an instance of an object.”

**Comment by JosonJiang** [comment]
SqlSugar 仓储方法  方式如何 注入？现在 有一个 BaseRepository<T> ；泛型类有公用方法 OrgDeptRepository 继承 引用然后报错 ；

System.AggregateException:“Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: XXXXXXX  Lifetime: Transient ImplementationType:XXXXX': Unable to resolve service for type 'XXXXXX。OrgDeptRepository' while attempting to activate 'XXXXXXX'.)”
