### ISSUE TITLE
Furion documentation - saas

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#93]

**Comment by xieyonghao1989** [comment]
大佬，请问一下在特定的方法中怎么取消租户查询？

**Comment by MonkSoul** [comment]
> @xieyonghao1989
> 大佬，请问一下在特定的方法中怎么取消租户查询？

.IgnoreQueryFilter() 即可。

**Comment by shuobuchulai** [comment]
请问下，仓储可以指定只加载某个租户的数据的吗

**Comment by MonkSoul** [comment]
> 请问下，仓储可以指定只加载某个租户的数据的吗

可以的，有 `DbRepository` 仓储，也就是针对特定的租户的仓储
