### ISSUE TITLE
Furion documentation - object-mapper

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#95]

**Comment by gandie5** [comment]
var orgs = await _sysOrgRep.DetachedEntities.Where(dataScopeList.Count > 0, u => dataScopeList.Contains(u.Id))
                                                        .Where(u => u.Status == CommonStatus.ENABLE)
                                                        .OrderBy(u => u.Sort)
                                                        .ProjectToType<OrgTreeNode>()
                                                        .ToListAsync();



为什么这个ProjectToType<OrgTreeNode>()是无效的，导致整个组织结构及树型结构数据都出不来了，去掉了就可以

**Comment by gandie5** [comment]
OrgTreeNode 两边我故意加了个空格，因为编辑器的原因，实际上是没有这空格哦，这是原框架里的代码，自己学习了一下，发现树型组织结构和组织结构列表出不来了，就是这个ProjectToType的原因

**Comment by gandie5** [comment]
另外，已配全局配置，仍然不起作用，这样会导到生成的SQL报错：
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'longtext) AS `Id`, CAST(`s`.`Pid` AS longtext) AS `Pid`, `s`.`Pids`, `s`.`Name`,' at line 1"
