### ISSUE TITLE
Furion documentation - cache

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#96]

**Comment by GHxiaohui** [comment]
![微信图片_20220625115154](https://user-images.githubusercontent.com/63650990/175757217-d1af1396-6344-44ab-8c52-7d8e12c1414a.jpg)
在form中获取不到缓存

**Comment by GHxiaohui** [comment]
![微信图片_20220625115206](https://user-images.githubusercontent.com/63650990/175757252-c5310aa9-ea27-4226-ae27-d81090226105.jpg)

**Comment by GHxiaohui** [comment]
pp2没有值
