### ISSUE TITLE
Furion documentation - auth-control

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#97]

**Comment by 18672794706** [comment]
不是很清楚如何在登录的时候使用，以及实现cookice+jwt两者满足其一的认证模式

**Comment by PrideJoy** [comment]
第三方授权自定义  else context.Fail();  这是能返回自定义状态码吗
throw Oops.Oh(1000).StatusCode(400);    // 设置错误码  返回的状态码直接500了

**Comment by shineleo** [comment]
在mvc下，尝试cookice+jwt总是不成功，文档说默认是Cookie ，结果显示如下错误：No authenticationScheme was specified, and there was no DefaultSignInScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).请教楼主该如何处理？

**Comment by MonkSoul** [comment]
> 在mvc下，尝试cookice+jwt总是不成功，文档说默认是Cookie ，结果显示如下错误：No authenticationScheme was specified, and there was no DefaultSignInScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action configureOptions).请教楼主该如何处理？

![image](https://user-images.githubusercontent.com/22766122/147714300-9f490402-35a5-434a-be4d-afa0876d9031.png)

**Comment by kinglinglive** [comment]
针对某个具体接口的用户授权，有什么推荐的方案

**Comment by PrideJoy** [comment]
> 针对某个具体接口的用户授权，有什么推荐的方案

IActionFilter

**Comment by DNLi303** [comment]
一直都是401 啥问题咯

**Comment by kinglinglive** [comment]
> @DNLi303
> 一直都是401 啥问题咯
> 请求头带上生成的token了吗？参考15.5.3

**Comment by ntuchenxy** [comment]
混合身份认证是什么意思？我想把token存入cookie来验证，是否要在浏览器js里再把token从cookie里取出来手动放入http头？

**Comment by ntuchenxy** [comment]
我在一个action上同时使用了ValidateAntiForgeryToken和Authorize，然后发现ValidateAntiForgeryToken似乎被覆盖了，ajax里header里已经把Authorization和RequestVerificationToken都加上了，单独的都能工作，但一起使用时ValidateAntiForgeryToken就不起作用，请问下这个问题怎么解决的

**Comment by HelloHsx** [comment]
请问前端获取不到响应头中的token怎么办

**Comment by kinglinglive** [comment]
> @HelloHsx
> 请问前端获取不到响应头中的token怎么办

存在但是前端取不到。可以参考下跨域的允许请求头配置
https://dotnetchina.gitee.io/furion/docs/cors#166-%E4%BD%BF%E7%94%A8-axios-%E5%89%8D%E7%AB%AF%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by HelloHsx** [comment]
> @kinglinglive
> > @HelloHsx
> > 请问前端获取不到响应头中的token怎么办
> 
> 存在但是前端取不到。可以参考下跨域的允许请求头配置
> https://dotnetchina.gitee.io/furion/docs/cors#166-%E4%BD%BF%E7%94%A8-axios-%E5%89%8D%E7%AB%AF%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

非常感谢！！

**Comment by MasterYuan418** [comment]
携带了`Authorization`头后依旧报401...咋办

**Comment by yw1987628** [comment]
JWT认证下 我用了Sentry错误跟踪 会有报错
“No authenticationScheme was specified, and there was no DefaultSignInScheme found”
实在是找不到原因 部分配置如下


![image](https://user-images.githubusercontent.com/11779480/175259786-c49e5f11-5507-4073-b73a-ea02a7299b5f.png)
![image](https://user-images.githubusercontent.com/11779480/175259853-c207aad5-098e-476b-ab2e-7806576b38a5.png)
![image](https://user-images.githubusercontent.com/11779480/175259942-83a87f2e-3d70-4017-a225-e06a87dfff9a.png)
![image](https://user-images.githubusercontent.com/11779480/175260028-ad41ea45-3b0f-4f24-8581-6b07f7b01e7b.png)
![image](https://user-images.githubusercontent.com/11779480/175260128-81826171-d2d3-4fb9-9564-c02f7a5aebd9.png)

**Comment by Schaffer-W** [comment]
在使用[Authorize]时，若服务器开启Windows身份验证，每次打开系统都会要求输入账户密码，这个怎么解决啊

**Comment by Schaffer-W** [comment]
> @MasterYuan418
>   携带了`Authorization`头后依旧报401...咋办

请求头格式是否这样的：Bearer {token}，
