### ISSUE TITLE
Furion documentation - view-engine

### ISSUE THREAD

**Issue by MonkSoul** [MonkSoul/Furion#99]

**Comment by xieyonghao1989** [comment]
大佬，视图引擎中，怎么对@符号转义喃，本身就想输出@Acount的字符，但是会报错误

**Comment by MonkSoul** [comment]
> 大佬，视图引擎中，怎么对@符号转义喃，本身就想输出@acount的字符，但是会报错误

两个 @@就可以了。如：`@@account`

**Comment by jiachunhui** [comment]
大佬给介绍一下，实现全站页面静态化，怎么用的呢，谢谢，找了相关信息也都没有成功

**Comment by yixiangling** [comment]
https://github.com/MonkSoul/Furion/blob/c15054b37af3e0dac20d729b7a629df43272f64c/framework/Furion/Templates/Extensions/StringRenderExtensions.cs#L41
返回值应当为string类型，这个返回void类型是不正确的

**Comment by MonkSoul** [comment]
> @yixiangling
> https://github.com/MonkSoul/Furion/blob/c15054b37af3e0dac20d729b7a629df43272f64c/framework/Furion/Templates/Extensions/StringRenderExtensions.cs#L41
> 返回值应当为string类型，这个返回void类型是不正确的

是的，应该是手误。。。，下次可以直接提交 Pull request 哦

**Comment by MonkSoul** [comment]
> https://github.com/MonkSoul/Furion/blob/c15054b37af3e0dac20d729b7a629df43272f64c/framework/Furion/Templates/Extensions/StringRenderExtensions.cs#L41
> 
> 
> 返回值应当为string类型，这个返回void类型是不正确的

已经修正，感谢：

![image](https://user-images.githubusercontent.com/22766122/168034771-3b9a3ea8-e86a-4c7e-b271-8f7b8b0de248.png)
